#!/bin/bash
# 部署博客到GitHub Pages

REPO="https://github.com/yisvin-netizen/mosquito-blog.git"

echo "========================================"
echo "  部署博客到 GitHub Pages"
echo "========================================"
echo ""
echo "请先在GitHub创建空仓库："
echo "1. 访问 https://github.com/new"
echo "2. Repository name: mosquito-blog"
echo "3. 选择 Public"
echo "4. 不要勾选任何初始化选项"
echo "5. 点击 Create repository"
echo ""
echo "创建完成后，运行以下命令："
echo ""
echo "========================================"
echo "  运行以下命令："
echo "========================================"
echo ""
echo "cd /root/.openclaw/workspace/knowledge-base/个人博客"
echo "git remote add origin $REPO"
echo 'git commit -m "Initial commit: 科技感个人博客"'
echo "git push -u origin master"
echo ""
echo "========================================"
echo "  开启 GitHub Pages："
echo "========================================"
echo ""
echo "1. 访问 https://github.com/yisvin-netizen/mosquito-blog/settings/pages"
echo "2. Source 选择 \"master\" 分支"
echo "3. 点击 Save"
echo "4. 等待1-2分钟"
echo ""
echo "你的博客将出现在："
echo "https://yisvin-netizen.github.io/mosquito-blog"
echo ""
